// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgcw8H0joEEz_w66MsfYSuYTHKZdBJtGI',
    appId: '1:1006774577580:web:21b98efaabc3c89fcb3209',
    messagingSenderId: '1006774577580',
    projectId: 'fit-sessions',
    authDomain: 'fit-sessions.firebaseapp.com',
    storageBucket: 'fit-sessions.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI4Qk3pALuDwH-31Wz8ubOKvPGBVMho-M',
    appId: '1:1006774577580:android:1eb2f4f9dc906139cb3209',
    messagingSenderId: '1006774577580',
    projectId: 'fit-sessions',
    storageBucket: 'fit-sessions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC-qzgMqTduxTNBGg33Wi8JJ4Gbc08OrI',
    appId: '1:1006774577580:ios:5f2c0aa07d96347bcb3209',
    messagingSenderId: '1006774577580',
    projectId: 'fit-sessions',
    storageBucket: 'fit-sessions.firebasestorage.app',
    iosBundleId: 'com.example.fitSessions',
  );
}
